### ISSUE TITLE
about the BleRedux.Android/BleServer.cs 

### ISSUE THREAD

**Issue by maxshng** [jameswestgate/BleRedux#1]
Dear Sir,

Should the implementation on the Android platform be implemented by our own? Notified that the ios platform has implemented. 

Sorry for bothering. Have a nice day.

Max

**Comment by jameswestgate** [comment]
Hi Max

I haven't tried the Android implementation yet, but I hear that it works ok as per the sample.

See this link for more details: [https://stackoverflow.com/questions/64160862/sending-data-between-two-phones-with-bluetooth-im-trying-to-use-aritchies-plu](https://stackoverflow.com/questions/64160862/sending-data-between-two-phones-with-bluetooth-im-trying-to-use-aritchies-plu)

**Comment by jameswestgate** [comment]
Hi again @maxshng 

There is now a commit with Android support. Please let me know if you have any issues.
